---
exclude_paths:
  - .cache/ # implicit unless exclude_paths is defined in config
  - .github/
loop_var_prefix: "{role}_"
var_naming_pattern: "^[a-z_][a-z0-9_]*$"
use_default_rules: true
skip_list:
  - skip_this_tag
enable_list:
  - empty-string-compare # opt-in
  - no-log-password # opt-in
  - no-same-owner # opt-in
  - yaml
warn_list:
  - skip_this_tag
  - experimental # experimental is included in the implicit list
