---
packages:
  - build-essential
  - linux-headers-{{ ansible_kernel }}
  - openssh-server
  - apache2
  - mariadb-server
  - mariadb-client
  - bison
  - flex
  - php7.4
  - php7.4-curl
  - php7.4-cli
  - php7.4-pdo
  - php7.4-mysql
  - php-pear
  - php7.4-gd
  - php7.4-mbstring
  - php7.4-intl
  - php7.4-xml
  - curl
  - cron
  - sox
  - libncurses5-dev
  - libssl-dev
  - mpg123
  - libxml2-dev
  - libnewt-dev
  - sqlite3
  - libsqlite3-dev
  - pkg-config
  - automake
  - libtool
  - autoconf
  - git
  - unixodbc-dev
  - uuid
  - uuid-dev
  - libasound2-dev
  - libogg-dev
  - libvorbis-dev
  - libicu-dev
  - libcurl4-openssl-dev
  - libical-dev
  - libneon27-dev
  - libsrtp2-dev
  - libspandsp-dev
  - libedit-dev
  - sudo
  - subversion
  - libtool-bin
  - unixodbc
  - dirmngr
  - sendmail-bin
  - sendmail
  - nodejs
  - xz-utils
  - python3-pip
  - net-tools
  ## Needed for debconf-set-selections
  - debconf-utils
