---
-
  name: Add Apt Key
  ansible.builtin.apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present
-
  name: Add Webmin Repo
  ansible.builtin.apt_repository:
    repo: deb http://download.webmin.com/download/repository sarge contrib
    state: present
-
  name: Install webmin
  ansible.builtin.apt:
    name: webmin
    update_cache: true
    state: present
